spring.application.name=spring_boot_application
server.port=7777
# bu file ichida siz connection qilishiz mumkin(database,redis, hibernate, jpa)
# configuratsiya qilish mumkin
# server port, app name yozish mumkin
# jwt token saqlash uchun, file absolute path saqlash uchun kerak boladi
# 2xil usulda yozsa boladi properties kengaytmani orniga application.yml file
############################################    DATABASE(POSTGRESQL)     ###############################################
spring.sql.init.platform=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/spring_boot_app
spring.datasource.username=postgres
spring.datasource.password=bexa
spring.jpa.hibernate.ddl-auto=update
jwt.token.secret=3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
api.info.title=University web application
api.info.version=1.0.0
api.info.description=Application for operation of University site
api.info.contact-name=t.me/programist_Spring
api.info.contact-email=bexruzizzatullayev@gmail.com
api.info.contact-url=https://hemis.uz
springdoc.swagger-ui.doc-expansion=none